REPO_URL=https://github.com/jimskon/coLearn-AI.git
REPO_BRANCH=main
APP_USER=liu17
APP_DIR=/opt/coLearn-AI
PORT=4000
DOMAIN=10.192.145.221
WWW_DOMAIN=10.192.145.221
DB_HOST=127.0.0.1
DB_PORT=3306
DB_NAME=colearn_db
DB_USER=colearn_user
DB_PASSWORD=joey
CLIENT_ORIGIN=http://10.192.145.221
SESSION_SECRET=aerretfdsg8fg8gfd897dfg879fgsd879sfg089fgssdfg
SERVICE_ACCOUNT_EMAIL=pogil-sheets-reader@colearn-ai.iam.gserviceaccount.com
APP_ROOT_NAME=Administrator
APP_ROOT_EMAIL=admin@kenyon.edu
APP_ROOT_PASSWORD=joey
BOOTSTRAP_APP_ROOT=1
SERVER_ENTRY=server/index.js
ENABLE_CXX_RUNNER=1
CXX_RUNNER_REPO_URL=https://github.com/jimskon/coLearn-AI-cxx-runner.git
CXX_RUNNER_DIR=/opt/cxx-runner
CXX_RUNNER_BRANCH=main
CXX_RUNNER_PORT=5055
OPENAI_API_KEY=sk-proj--B2P23M4P_b-IxX5GK-QJ60SmmNB4hGMBgOrRf6_ufUlVNSOSCmOr5nJWjYboHP0ho78i7bRDOT3B\
lbkFJi-vohO5sFqeHiwbMuwRY3gBSrDHkB70dd8ZRcr1CMZo2LMP29LbobN7tPdgcp3JLzO6RoERgcA
EMAIL_USER=pogilregistra@gmail.com
EMAIL_PASS=lrugxjlhydaxlqux
