/**
 * visualEditorEngine.js
 *
 * EER (Extract-Edit-Replace) engine and document model builder for the
 * coLearn-AI Visual Activity Editor.
 *
 * Design principle: every mutation follows Extract → form edit → Replace.
 * No AI. All markup generated by deterministic templates (markupTemplates.js).
 * Two validation passes ensure the document stays parse-clean.
 */

import { parseSheetToBlocks } from './parseSheet.jsx';

// ─── Constants ─────────────────────────────────────────────────────────────

export const PLACEHOLDER_PREFIX = '% [VISUAL-EDITOR PLACEHOLDER:';

// ─── Document Model Builder ────────────────────────────────────────────────

/**
 * Build a structured document model from raw source text.
 *
 * Returns:
 *   {
 *     preamble: PreambleValues,
 *     sections: Section[],
 *     parseIssues: Issue[],
 *   }
 *
 * Where Section = { key, rawTitle, startLine, endLine, groups: Group[] }
 * Group = { groupId, rawTitle, startLine, endLine, questions: Question[] }
 * Question = { id, rawPrompt, startLine, endLine, responseSummary, feedbackPrompt }
 */
export function buildDocumentModel(sourceText) {
  const sourceLines = String(sourceText || '').split('\n');
  let parsed;
  try {
    parsed = parseSheetToBlocks(sourceLines, { returnIssues: true });
  } catch (e) {
    return { preamble: {}, sections: [], parseIssues: [{ type: 'error', message: String(e) }] };
  }

  const blocks = Array.isArray(parsed?.blocks) ? parsed.blocks
               : Array.isArray(parsed) ? parsed : [];
  const parseIssues = Array.isArray(parsed?.issues) ? parsed.issues : [];
  const meta = parsed?.meta || {};

  const preamble = extractPreambleValues(sourceLines, meta);
  const sections = buildSectionTree(blocks, sourceLines);

  return { preamble, sections, parseIssues };
}

function extractPreambleValues(sourceLines, meta) {
  const get = (tag) => {
    for (const line of sourceLines) {
      const t = line.trim();
      const m = t.match(new RegExp(`^\\\\${tag}\\{([\\s\\S]*?)\\}$`));
      if (m) return m[1];
    }
    return '';
  };
  return {
    title: get('title'),
    name: get('name'),
    mode: meta.mode || 'group',
    studentLevel: get('studentlevel'),
    activityContext: get('activitycontext'),
    aiCodeGuidance: get('aicodeguidance'),
    aiMode: meta.aiMode || 'no-positive',
    language: get('language'),
    retries: get('retries'),
  };
}

function findSectionLines(sourceLines) {
  // Returns array of 1-based line numbers where \section{ appears
  const result = [];
  for (let i = 0; i < sourceLines.length; i++) {
    if (/^\s*\\section\*?\{/.test(sourceLines[i])) {
      result.push(i + 1);
    }
  }
  return result;
}

function extractRawTitle(sourceLines, lineNo, tagPattern) {
  if (!lineNo || lineNo > sourceLines.length) return '';
  const m = (sourceLines[lineNo - 1] || '').trim().match(tagPattern);
  return m ? m[1] : '';
}

function describeResponses(block) {
  const parts = [];
  if (block.textResponse) parts.push('text');
  if (block.pythonBlock)  parts.push('Python');
  if (block.cppBlock)     parts.push('C++');
  if (block.multipleChoice) {
    parts.push(block.multipleChoice.selectionMode === 'multiple' ? 'MC survey' : 'MC graded');
  }
  return parts.length ? parts.join(', ') : 'informational';
}

function buildSectionTree(blocks, sourceLines) {
  const sectionLineNos = findSectionLines(sourceLines);
  const sections = [];
  let sectionIdx = -1;
  let groupIdx = -1;
  let sectionCount = 0;

  // We need an implicit "default" section when no \section tags exist
  const ensureDefaultSection = () => {
    if (sectionIdx < 0) {
      sections.push({
        key: 'section-implicit',
        rawTitle: '',
        startLine: 1,
        endLine: sourceLines.length,
        isImplicit: true,
        groups: [],
      });
      sectionIdx = 0;
    }
  };

  const finalizeSection = () => {
    groupIdx = -1;
  };

  for (const block of blocks) {
    if (block.type === 'section') {
      finalizeSection();
      sectionCount++;
      const startLine = sectionLineNos[sectionCount - 1] || null;
      // endLine filled in after loop
      sections.push({
        key: block.key || `section-${sectionCount}`,
        rawTitle: extractRawTitle(sourceLines, startLine, /^\\section\*?\{([\s\S]*?)\}/),
        startLine,
        endLine: null,
        isImplicit: false,
        groups: [],
      });
      sectionIdx = sections.length - 1;

    } else if (block.type === 'groupIntro') {
      ensureDefaultSection();
      const groupStartLine = block.sourceMeta?.groupLine || null;
      const groupEndLine   = block.sourceMeta?.endGroupLine || null;
      sections[sectionIdx].groups.push({
        groupId: block.groupId,
        rawTitle: extractRawTitle(sourceLines, groupStartLine, /^\\questiongroup\{([\s\S]*?)\}/),
        startLine: groupStartLine,
        endLine: groupEndLine,
        questions: [],
      });
      groupIdx = sections[sectionIdx].groups.length - 1;

    } else if (block.type === 'question') {
      ensureDefaultSection();
      if (groupIdx < 0 || groupIdx >= sections[sectionIdx].groups.length) continue;

      const qStartLine = block.sourceMeta?.questionLine || null;
      const qEndLine   = block.sourceMeta?.endQuestionLine || null;

      // Extract raw prompt from source line
      const rawPrompt = qStartLine
        ? extractRawTitle(sourceLines, qStartLine, /^\\question\{([\s\S]*?)\}/)
        : '';

      sections[sectionIdx].groups[groupIdx].questions.push({
        id: block.id,
        rawPrompt,
        startLine: qStartLine,
        endLine: qEndLine,
        responseSummary: describeResponses(block),
        feedbackPrompt: block.feedbackPrompt || '',
      });
    }
  }

  // Fill section end lines
  for (let i = 0; i < sections.length; i++) {
    if (i + 1 < sections.length) {
      sections[i].endLine = (sections[i + 1].startLine || 2) - 1;
    } else {
      sections[i].endLine = sourceLines.length;
    }
  }

  return sections;
}

// ─── Preamble Range ────────────────────────────────────────────────────────

/**
 * Find the line range (1-based, inclusive) of the preamble block.
 * The preamble is everything before the first \section or \questiongroup.
 */
export function findPreambleRange(sourceLines) {
  for (let i = 0; i < sourceLines.length; i++) {
    const t = sourceLines[i].trim();
    if (t.startsWith('\\section') || t.startsWith('\\questiongroup')) {
      if (i === 0) return { startLine: 1, endLine: 1 };
      return { startLine: 1, endLine: i };
    }
  }
  return { startLine: 1, endLine: sourceLines.length };
}

// ─── Raw Value Extractors ──────────────────────────────────────────────────

/**
 * Extract structured form values from raw source lines of a question block.
 * rawLines: array of strings from \question{...} through \endquestion (inclusive).
 */
export function parseRawQuestion(rawLines) {
  const result = {
    prompt: '',
    aiMode: '',
    responseType: 'none',
    responseValues: {},
    feedbackPrompt: '',
    sampleResponses: '',
    followupPrompt: '',
    scoreBlock: null,
  };

  if (!rawLines || rawLines.length === 0) return result;

  // First line: \question{prompt}
  const firstTrimmed = rawLines[0].trim();
  const qm = firstTrimmed.match(/^\\question\{([\s\S]*?)\}$/);
  result.prompt = qm ? qm[1] : firstTrimmed;

  let inPython = false, inCpp = false, inMC = false, inScore = false;
  let codeLines = [], mcChoices = [], scoreLines = [];
  let codeTag = '', codeTimeout = null;
  let mcCorrect = '', mcSurvey = false;

  for (let i = 1; i < rawLines.length; i++) {
    const t = rawLines[i].trim();
    const raw = rawLines[i];

    // Inside code block
    if (inPython) {
      if (t === '\\endpython') {
        inPython = false;
        result.responseType = 'python';
        result.responseValues = { code: codeLines.join('\n'), timeout: codeTimeout };
      } else {
        codeLines.push(raw);
      }
      continue;
    }
    if (inCpp) {
      if (t === '\\endcpp') {
        inCpp = false;
        result.responseType = 'cpp';
        result.responseValues = { code: codeLines.join('\n'), timeout: codeTimeout };
      } else {
        codeLines.push(raw);
      }
      continue;
    }
    if (inScore) {
      if (t === '\\endscore') {
        inScore = false;
        if (result.scoreBlock) result.scoreBlock.rubric = scoreLines.join('\n');
      } else {
        scoreLines.push(raw);
      }
      continue;
    }

    // Tags
    if (/^\\aimode\{/.test(t)) {
      const m = t.match(/^\\aimode\{(.*?)\}$/);
      result.aiMode = m ? m[1] : '';

    } else if (/^\\textresponse\{/.test(t)) {
      const m = t.match(/^\\textresponse\{(\d+)\}$/);
      result.responseType = 'text';
      result.responseValues = { lines: m ? parseInt(m[1], 10) : 4 };

    } else if (/^\\python(\{.*\})?$/.test(t)) {
      inPython = true;
      codeLines = [];
      const m = t.match(/^\\python\{(\d+)\}$/);
      codeTimeout = m ? m[1] : null;

    } else if (/^\\cpp(\{.*\})?$/.test(t)) {
      inCpp = true;
      codeLines = [];
      const m = t.match(/^\\cpp\{(\d+)\}$/);
      codeTimeout = m ? m[1] : null;

    } else if (/^\\multiplechoice\{multiple\}/.test(t)) {
      inMC = true;
      mcSurvey = true;
      mcChoices = [];
      result.responseType = 'mc_survey';

    } else if (/^\\multiplechoice\{/.test(t)) {
      inMC = true;
      mcSurvey = false;
      const m = t.match(/^\\multiplechoice\{(.*?)\}$/);
      mcCorrect = m ? m[1] : '';
      mcChoices = [];
      result.responseType = 'mc_graded';

    } else if (/^\\choice\{/.test(t) && inMC) {
      const m = t.match(/^\\choice\{(.*?)\}$/);
      if (m) mcChoices.push(m[1]);

    } else if (t === '\\endmultiplechoice' && inMC) {
      inMC = false;
      result.responseValues = mcSurvey
        ? { choices: mcChoices }
        : { correctAnswer: mcCorrect, choices: mcChoices };

    } else if (/^\\feedbackprompt\{/.test(t)) {
      const m = t.match(/^\\feedbackprompt\{([\s\S]*?)\}$/);
      result.feedbackPrompt = m ? m[1] : '';

    } else if (/^\\sampleresponses\{/.test(t)) {
      const m = t.match(/^\\sampleresponses\{([\s\S]*?)\}$/);
      result.sampleResponses = m ? m[1] : '';

    } else if (/^\\followupprompt\{/.test(t)) {
      const m = t.match(/^\\followupprompt\{([\s\S]*?)\}$/);
      result.followupPrompt = m ? m[1] : '';

    } else if (/^\\score\{/.test(t)) {
      const m = t.match(/^\\score\{(\d+),([\w]+)\}$/);
      if (m) {
        result.scoreBlock = { points: parseInt(m[1], 10), type: m[2], rubric: '' };
        inScore = true;
        scoreLines = [];
      }
    }
  }

  return result;
}

/**
 * Extract preamble form values from raw source lines (before first section/group).
 */
export function parseRawPreamble(sourceLines) {
  const get = (tag) => {
    for (const line of sourceLines) {
      const t = line.trim();
      const m = t.match(new RegExp(`^\\\\${tag}\\{([\\s\\S]*?)\\}$`));
      if (m) return m[1];
    }
    return '';
  };
  const hasMode = (m) => sourceLines.some((l) => l.trim() === `\\mode{${m}}`);

  return {
    title: get('title'),
    name: get('name'),
    mode: hasMode('test') ? 'test' : hasMode('demo') ? 'demo'
        : hasMode('assignment') ? 'assignment' : 'group',
    retries: get('retries'),
    studentLevel: get('studentlevel'),
    activityContext: get('activitycontext'),
    aiCodeGuidance: get('aicodeguidance'),
    aiMode: get('aimode') || 'no-positive',
    language: get('language'),
  };
}

// ─── EER Engine ───────────────────────────────────────────────────────────

/**
 * Extract lines for a range, replacing them with an inert placeholder comment.
 *
 * @param {string} sourceText
 * @param {{ startLine: number, endLine: number }} lineRange  1-based, inclusive
 * @param {string} label
 * @returns {{ updatedSource: string, placeholder: string, backup: string }}
 */
export function extractElement(sourceText, lineRange, label = 'element') {
  const lines = String(sourceText || '').split('\n');
  const { startLine, endLine } = lineRange;

  if (!Number.isInteger(startLine) || !Number.isInteger(endLine)
      || startLine < 1 || endLine < startLine || endLine > lines.length) {
    throw new Error(
      `extractElement: invalid range ${startLine}–${endLine} for "${label}" ` +
      `(document has ${lines.length} lines)`
    );
  }

  const placeholder = `${PLACEHOLDER_PREFIX} ${label} lines ${startLine}-${endLine}]`;

  const updatedLines = [
    ...lines.slice(0, startLine - 1),
    placeholder,
    ...lines.slice(endLine),
  ];

  return {
    updatedSource: updatedLines.join('\n'),
    placeholder,
    backup: sourceText,
  };
}

/**
 * Splice new markup in where the placeholder currently is.
 * Throws if the placeholder is not found (document was modified concurrently).
 *
 * @param {string} sourceText
 * @param {string} placeholder  exact string returned by extractElement
 * @param {string} newMarkup
 * @returns {string}
 */
export function replaceElement(sourceText, placeholder, newMarkup) {
  const lines = String(sourceText || '').split('\n');
  const idx = lines.indexOf(placeholder);
  if (idx === -1) {
    throw new Error(
      'Visual editor placeholder not found. ' +
      'The document may have been modified while an edit was in progress.'
    );
  }
  const newLines = String(newMarkup || '').split('\n');
  return [...lines.slice(0, idx), ...newLines, ...lines.slice(idx + 1)].join('\n');
}

/**
 * Delete the lines in lineRange from sourceText.
 * Full-document validation should be run after this.
 *
 * @param {string} sourceText
 * @param {{ startLine: number, endLine: number }} lineRange
 * @returns {string}
 */
export function deleteElement(sourceText, lineRange) {
  const lines = String(sourceText || '').split('\n');
  const { startLine, endLine } = lineRange;
  return [
    ...lines.slice(0, startLine - 1),
    ...lines.slice(endLine),
  ].join('\n');
}

/**
 * Insert newMarkup before a given line number (1-based).
 * Used for "Add" operations.
 *
 * @param {string} sourceText
 * @param {number} beforeLine
 * @param {string} newMarkup
 * @returns {string}
 */
export function insertBeforeLine(sourceText, beforeLine, newMarkup) {
  const lines = String(sourceText || '').split('\n');
  const idx = Math.max(0, Math.min(lines.length, beforeLine - 1));
  const newLines = String(newMarkup || '').split('\n');
  return [...lines.slice(0, idx), ...newLines, ...lines.slice(idx)].join('\n');
}

/**
 * Check whether sourceText currently contains an unresolved placeholder.
 * Returns the placeholder string if found, null otherwise.
 */
export function findPendingPlaceholder(sourceText) {
  const lines = String(sourceText || '').split('\n');
  return lines.find((l) => l.startsWith(PLACEHOLDER_PREFIX)) || null;
}

// ─── Validation ───────────────────────────────────────────────────────────

/**
 * Pass 1 — validate generated markup in isolation.
 * Wraps the markup in a minimal valid document skeleton before parsing.
 *
 * @param {string} markup
 * @param {'preamble'|'section'|'group'|'question'} wrapAs
 * @returns {Issue[]}
 */
export function validateGeneratedMarkup(markup, wrapAs = 'question') {
  let wrapped;
  switch (wrapAs) {
    case 'preamble':
      wrapped = `${markup}\n\\section{Test}\n\\questiongroup{Test}\n\\endquestiongroup`;
      break;
    case 'section':
      wrapped = `\\title{t}\n\\name{n}\n${markup}\n\\questiongroup{Test}\n\\endquestiongroup`;
      break;
    case 'group':
      wrapped = `\\title{t}\n\\name{n}\n\\section{Test}\n${markup}\n\\endquestiongroup`;
      break;
    case 'question':
    default:
      wrapped = `\\title{t}\n\\name{n}\n\\section{Test}\n\\questiongroup{Test}\n${markup}\n\\endquestiongroup`;
      break;
  }

  try {
    const parsed = parseSheetToBlocks(wrapped.split('\n'), { returnIssues: true });
    return Array.isArray(parsed?.issues) ? parsed.issues : [];
  } catch (e) {
    return [{ type: 'error', message: String(e) }];
  }
}

/**
 * Pass 2 — validate the full document after a splice.
 *
 * @param {string} sourceText
 * @returns {Issue[]}
 */
export function validateFullDocument(sourceText) {
  try {
    const parsed = parseSheetToBlocks(
      String(sourceText || '').split('\n'),
      { returnIssues: true }
    );
    return Array.isArray(parsed?.issues) ? parsed.issues : [];
  } catch (e) {
    return [{ type: 'error', message: String(e) }];
  }
}
